spring.application.name=demo
spring.datasource.url=jdbc:mariadb://localhost:3306/mueblearte_db
spring.datasource.username=mueblearte
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#JPA/hibernate
spring.jpa.hibernate.ddl-auto=update
#logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# File upload config
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB